// flow-typed signature: 917c89f5cca5250c97e38259dfa7f154
// flow-typed version: <<STUB>>/chokidar-cli_v^1.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chokidar-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chokidar-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chokidar-cli/test/dir/a' {
  declare module.exports: any;
}

declare module 'chokidar-cli/test/dir/b' {
  declare module.exports: any;
}

declare module 'chokidar-cli/test/dir/subdir/c' {
  declare module.exports: any;
}

declare module 'chokidar-cli/test/test-all' {
  declare module.exports: any;
}

declare module 'chokidar-cli/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chokidar-cli/index' {
  declare module.exports: $Exports<'chokidar-cli'>;
}
declare module 'chokidar-cli/index.js' {
  declare module.exports: $Exports<'chokidar-cli'>;
}
declare module 'chokidar-cli/test/dir/a.js' {
  declare module.exports: $Exports<'chokidar-cli/test/dir/a'>;
}
declare module 'chokidar-cli/test/dir/b.js' {
  declare module.exports: $Exports<'chokidar-cli/test/dir/b'>;
}
declare module 'chokidar-cli/test/dir/subdir/c.js' {
  declare module.exports: $Exports<'chokidar-cli/test/dir/subdir/c'>;
}
declare module 'chokidar-cli/test/test-all.js' {
  declare module.exports: $Exports<'chokidar-cli/test/test-all'>;
}
declare module 'chokidar-cli/utils.js' {
  declare module.exports: $Exports<'chokidar-cli/utils'>;
}
