// flow-typed signature: d9434f51bfcb9000f66a63b7b14b5abf
// flow-typed version: <<STUB>>/logatim_v^0.9.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logatim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'logatim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logatim/dist/logatim.amd.min' {
  declare module.exports: any;
}

declare module 'logatim/dist/logatim.commonjs2.min' {
  declare module.exports: any;
}

declare module 'logatim/dist/logatim.umd.min' {
  declare module.exports: any;
}

declare module 'logatim/dist/logatim.var.min' {
  declare module.exports: any;
}

declare module 'logatim/lib/constants' {
  declare module.exports: any;
}

declare module 'logatim/lib/levels' {
  declare module.exports: any;
}

declare module 'logatim/lib/logatim' {
  declare module.exports: any;
}

declare module 'logatim/lib/logs' {
  declare module.exports: any;
}

declare module 'logatim/lib/utils' {
  declare module.exports: any;
}

declare module 'logatim/test/levels-prime' {
  declare module.exports: any;
}

declare module 'logatim/test/test-levels' {
  declare module.exports: any;
}

declare module 'logatim/test/test-logs' {
  declare module.exports: any;
}

declare module 'logatim/test/test-styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logatim/dist/logatim.amd.min.js' {
  declare module.exports: $Exports<'logatim/dist/logatim.amd.min'>;
}
declare module 'logatim/dist/logatim.commonjs2.min.js' {
  declare module.exports: $Exports<'logatim/dist/logatim.commonjs2.min'>;
}
declare module 'logatim/dist/logatim.umd.min.js' {
  declare module.exports: $Exports<'logatim/dist/logatim.umd.min'>;
}
declare module 'logatim/dist/logatim.var.min.js' {
  declare module.exports: $Exports<'logatim/dist/logatim.var.min'>;
}
declare module 'logatim/lib/constants.js' {
  declare module.exports: $Exports<'logatim/lib/constants'>;
}
declare module 'logatim/lib/levels.js' {
  declare module.exports: $Exports<'logatim/lib/levels'>;
}
declare module 'logatim/lib/logatim.js' {
  declare module.exports: $Exports<'logatim/lib/logatim'>;
}
declare module 'logatim/lib/logs.js' {
  declare module.exports: $Exports<'logatim/lib/logs'>;
}
declare module 'logatim/lib/utils.js' {
  declare module.exports: $Exports<'logatim/lib/utils'>;
}
declare module 'logatim/test/levels-prime.js' {
  declare module.exports: $Exports<'logatim/test/levels-prime'>;
}
declare module 'logatim/test/test-levels.js' {
  declare module.exports: $Exports<'logatim/test/test-levels'>;
}
declare module 'logatim/test/test-logs.js' {
  declare module.exports: $Exports<'logatim/test/test-logs'>;
}
declare module 'logatim/test/test-styles.js' {
  declare module.exports: $Exports<'logatim/test/test-styles'>;
}
