// flow-typed signature: 78217d41c7d4c4a86dc381c1b3c8fb8e
// flow-typed version: <<STUB>>/shake.js_v1.2.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shake.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shake.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shake.js/shake' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shake.js/shake.js' {
  declare module.exports: $Exports<'shake.js/shake'>;
}
